### ISSUE TITLE
Meteor pages kills spiderable

### ISSUE THREAD

**Issue by MaazAli** [alethes/meteor-pages#111] opened 2014-12-26 12:10 UTC
```
TypeError: 'undefined' is not a function (evaluating 'args[last].bind(this)')

  http://localhost:3000/packages/alethes_pages.js?880d02062f225bbd69e5852c934f32f79bbaa468:323
  http://localhost:3000/packages/alethes_pages.js?880d02062f225bbd69e5852c934f32f79bbaa468:248
  http://localhost:3000/packages/alethes_pages.js?880d02062f225bbd69e5852c934f32f79bbaa468:234
  http://localhost:3000/packages/alethes_pages.js?880d02062f225bbd69e5852c934f32f79bbaa468:391
  http://localhost:3000/packages/alethes_pages.js?880d02062f225bbd69e5852c934f32f79bbaa468:169 in Pages
  http://localhost:3000/collections/anime.js?7e438b069e082d5588772bbc7d6075190e5aa0a2:295
  http://localhost:3000/collections/anime.js?7e438b069e082d5588772bbc7d6075190e5aa0a2:469
```

If I remove the package spiderable doesn't throw that error when I go to `/?_escaped_fragment_=`

**Comment by ivankravchenko** [comment] 2015-01-19 17:04
+1

**Comment by rantav** [comment] 2015-01-21 11:57
+1, this happens to me too. Is there a workaround? 
I don't directly use meteor-pages, but it gets included indirectly by https://github.com/yogiben/meteor-admin which I do use

**Comment by alethes** [comment] 2015-02-18 23:56
This is because of https://github.com/ariya/phantomjs/issues/10522. The issue is fixed in PhantomJS 2. In earlier versions, you could use https://github.com/kdimatteo/bind-polyfill.

**Closed by alethes** 2015-02-18 23:56 UTC

**Comment by GiraffeSlacks** [comment] 2015-02-26 01:36
@alethes Forgive me but what does PhantomJS have to do with this? I don't use PhantomJS that I'm aware of so I can't upgrade it to version 2 (that I'm aware of.)

**Comment by alethes** [comment] 2015-02-26 02:43
`spiderable` is based on PhantomJS. Anyway, I started moving from native `bind` to `_.bind`, which works fine with PhantomJS 1.*.

**Comment by GiraffeSlacks** [comment] 2015-02-26 04:20
Thanks for the explanation. I'm not using `spiderable`.

**Comment by olivierpascal** [comment] 2015-05-10 15:03
Hi, +1 same error with Spiderable and the last version of meteor-pages

```

TypeError: 'undefined' is not a function (evaluating 'args[last].bind(this)')

  http://localhost/packages/alethes_pages.js?c34e40f7b75aeda63059eaf986e5f32eddb1b152:333
  http://localhost/packages/alethes_pages.js?c34e40f7b75aeda63059eaf986e5f32eddb1b152:255
  http://localhost/packages/alethes_pages.js?c34e40f7b75aeda63059eaf986e5f32eddb1b152:242
  http://localhost/packages/alethes_pages.js?c34e40f7b75aeda63059eaf986e5f32eddb1b152:401
  http://localhost/packages/alethes_pages.js?c34e40f7b75aeda63059eaf986e5f32eddb1b152:408
  http://localhost/packages/alethes_pages.js?c34e40f7b75aeda63059eaf986e5f32eddb1b152:178 in Pages
  http://localhost/lib/env.coffee.js?7ef3989cd8c6cff155326d8f8fe00938f88dfe0c:43
  http://localhost/lib/env.coffee.js?7ef3989cd8c6cff155326d8f8fe00938f88dfe0c:48
```

Is this bug supposed to be fixed?
